const SCREENS = {
  AUTHROUTES: "AuthRoutes",
  LOGINSCREEN: "LoginScreen",
  SIGNUPSCREEN: "SignupScreen",
  MAINROUTES: "MainRoutes",
  LISTINGBOOKING: "ListingBooking",
  VIEWHISTORY: "ViewHistory",
  BOOKINGDETAIL: "BookingDetail",
  INVOICEDETAIL: "InvoiceDetail",
  RECEIPTDETAIL: "ReceiptDetail",
  FORGOTPASSWORD: "ForgotPassword",
  VIEWALLAVAILABLELISTING: "ViewAllAvailableListings",
  VIEWGALLERY: "ViewGallery",
  BOOKNOW: "BookNow",
  REVENUEDETAIL: "RevenueDetail",
  DUEONOWNERLIST: "DueOnOwnerList",
  ALLBOOKINGREVENUE: "AllBookingRevenue",
  DUETAB: "DueTab",
  MONTHLYTAB: "MonthlyTab",
  EXTENDBOOK: "ExtendBook",
  UTILITIESLIST: "UtilitiesList",
  REVENUETAB: "RevenueTab",
  BOOKNOWCUSTOMER: "BookNowCustomer",
  PROPERTYDETAIL: "PropertyDetail",
  DETAILDASHBOARD: "DetailDashbaord",
  PAYMENTPLAN: "PaymentPlan",
  CUSTOMER: "Customer",
  STATSLISTING: "StatsListing",
  DELETEACCOUNT: "DeleteAccount",
  RECEIPTDETAIL: "ReceiptDetail",
  PRICESETUP: "PriceSetup",
  TOTALAVAILABLE: "TotalAvailable",
  TOTALAVAILABLELISTINGS: "TotalAvailableListings",
  PRICEDETAIL: "PriceDetail",
  POWERBI: "PowerBI",
  CREATECUSTOMER: "CreateCustomer",
  CREATERECEIPT: "CreateReceipt",
  CREATEPAYMENT: "CreatePayment",
  DASHBOARDLISTING: "DashboardListing",
  COMMISSIONDETAIL: "CommissionDetail",
};

export { SCREENS };
